### PR TITLE
Added instructions to dropdown to show that they can be typed into. Created new FilteredSelect component to do so.

### LINKED ISSUE #62: Make it more clear that users can type in dropdowns to filter their options

### PR DESCRIPTION
**Pull request by julian-george**

### CODE REVIEW

**Comment by julian-george** [comment]
Make sure the changes to package.json and eslint aren't changed, since theyre to make it work on windows

**Review by dmwhang — COMMENTED** [review]
Hey, giving it a look over rn. Could you .gitignore the package.json for now? Think it is the cuase of the windows vs mac deploying issues.

**Comment by dmwhang** [comment]
After initial look through, good start, but you need to incorporate this on the student profile component as well:
Screen Shot 2021-04-30 at 12 21 46 PM
(this is from the student profile page)

I like that you were able to incorporate different text, but the feedback we received was that we need to encourage people to type in different classes, industries, skills to search them and if they can't find it to create one. So put in text that says something like "type or create" or something that encourages those behaviors. (Ping me on slack if that didnt make sense.)
Screen Shot 2021-04-30 at 12 21 19 PM

**Comment by julian-george** [comment]
I changed the "select" language to use "add" more for the cases you mentioned that warrant them, both in the inactive placeholder and the active placeholder. The one issue would be with the dropdowns where you can select more than one, since the placeholder disappears after the boxes are added inside of the select. Still, if you saw the instructions and were able to add one thing, you'd probably be able to do that again. LMK if you think anything is still not self-explanatory.

**Comment by julian-george** [comment]
image
image
image

Here's some screenshots of the changes, note the use of "add" a lot more and the issue with the placeholder disappearing after adding something to multi select

**Comment by dmwhang** [comment]
Slacked you this but just to keep it on record:
- Good job overall! Enjoyed the easy ui of your approach and the use of a new component
- remember to include screenshots for ui updates
- double check the edits that you are pushing (remember this is going to merge with the main branch!)

**Pull request merged**
